apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${PROJECT_NAME}
labels:
  template: api-build
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: dotnet-31-rhel7
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: registry.redhat.io/dotnet/dotnet-31-rhel7:3.1-24
          name: "3.1"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: postgresql-10-rhel8
      labels:
        shared: "true"
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: registry.redhat.io/rhel8/postgresql-10
          name: "1"
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
      postCommit: {}
      source:
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        type: Git
        contextDir: "Server"
      strategy:
        sourceStrategy:
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: SchoolBusAPI/SchoolBusAPI.csproj
          from:
            kind: ImageStreamTag
            name: "dotnet-31-rhel7:3.1"
        type: Source
parameters:
  - description: Name of the project (SCHOOLBUS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "sb"
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: false
    value: "api"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: "1.4"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: "https://github.com/bcgov/schoolbus.git"
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: "master"
