apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ${NAME}-build-template
labels:
  template: backup-build
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      creationTimestamp: null
      labels:
        shared: "true"
      name: ${NAME}
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      creationTimestamp: null
      labels:
        build: ${NAME}${SUFFIX}
      name: ${NAME}${SUFFIX}
    spec:
      nodeSelector: null
      completionDeadlineSeconds: 600
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${VERSION}
      resources:
        limits:
          cpu: 2
          memory: 4Gi
        requests:
          cpu: 1
          memory: 2Gi
      postCommit: {}
      source:
        git:
          uri: ${SOURCE_REPOSITORY_URL}
          ref: ${SOURCE_REPOSITORY_REF}
        type: Git
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        dockerStrategy:
          dockerfilePath: ${DOCKER_FILE_PATH}
        type: "Docker"
parameters:
  - description: A name used for all objects
    displayName: Name
    name: NAME
    required: false
    value: "backup"
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: false
    value: "1.4"
  - description: SOURCE_REPOSITORY_URL
    displayName: SOURCE_REPOSITORY_URL
    name: SOURCE_REPOSITORY_URL
    required: false
    value: "https://github.com/BCDevOps/backup-container.git"
  - description: SOURCE_REPOSITORY_REF
    displayName: SOURCE_REPOSITORY_REF
    name: SOURCE_REPOSITORY_REF
    required: false
    value: ""
  - description: SOURCE_CONTEXT_DIR
    displayName: SOURCE_CONTEXT_DIR
    name: SOURCE_CONTEXT_DIR
    required: false
    value: "docker"
  - description: DOCKER_FILE_PATH
    displayName: DOCKER_FILE_PATH
    name: DOCKER_FILE_PATH
    required: true
    value: "Dockerfile"
