kind: Template
apiVersion: v1
metadata:
  name: ${PROJECT_NAME}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}${SUFFIX}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        type: Recreate
        recreateParams:
          timeoutSeconds: 600
      template:
        metadata:
          name: ${NAME}${SUFFIX}
          labels:
            deploymentconfig: ${NAME}${SUFFIX}
        spec:
          containers:
            - image: docker-registry.default.svc:5000/tran-schoolbus-tools/${IMAGE_STREAM_TAG}
              imagePullPolicy: IfNotPresent
              name: ${NAME}${SUFFIX}
              env:
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: database-user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: database-password
                - name: POSTGRESQL_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${NAME}${SUFFIX}
                      key: admin-password
                - name: POSTGRESQL_DATABASE
                  value: ${POSTGRESQL_DATABASE_NAME}
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources:
                requests:
                  cpu: 10m
                  memory: 128Mi
                limits:
                  cpu: 250m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: "${NAME}-${ENV}-data"
                  mountPath: "/var/lib/pgsql/data"
              livenessProbe:
                tcpSocket:
                  port: 5432
                initialDelaySeconds: 30
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              readinessProbe:
                exec:
                  command:
                    - "/bin/sh"
                    - "-i"
                    - "-c"
                    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c
                      'SELECT 1'
                initialDelaySeconds: 5
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: "${NAME}-${ENV}-data"
              persistentVolumeClaim:
                claimName: ${NAME}-${ENV}
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}${SUFFIX}
            from:
              kind: ImageStreamTag
              name: ${IMAGE_STREAM_TAG}
              namespace: tran-schoolbus-tools
          type: ImageChange
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${NAME}-${ENV}
    selector:
      deploymentconfig: ${NAME}-${ENV}
    spec:
      storageClassName: "${PERSISTENT_VOLUME_CLASS}"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "${PERSISTENT_VOLUME_SIZE}"
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}${SUFFIX}
    spec:
      ports:
        - name: postgresql
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        deploymentconfig: ${NAME}${SUFFIX}
parameters:
  - description: Name of the project (SCHOOLBUS)
    displayName: PROJECT_NAME
    name: PROJECT_NAME
    required: true
    value: "sb"
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the PostgreSQL instance.
    required: true
    value: db
  - description: A name suffix used for all objects
    displayName: Suffix
    name: SUFFIX
    required: false
    value: "-dev"
  - description: Environment short name (dev,test,uat,prod)
    displayName: ENV
    name: ENV
    required: false
    value: "dev"
  - description: A version used for the image tags
    displayName: version
    name: VERSION
    required: true
    value: "v1.0.0"
  - description: ImageStreamTag
    displayName: ImageStreamTag
    name: IMAGE_STREAM_TAG
    value: "postgresql-10-rhel8:1"
  - name: POSTGRESQL_DATABASE_NAME
    displayName: PostgreSQL Database Name
    description: The name of the PostgreSQL database.
    required: true
    value: schoolbus
  - name: PERSISTENT_VOLUME_SIZE
    displayName: Persistent Volume Size
    description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
    required: true
    value: 5Gi
  - name: PERSISTENT_VOLUME_CLASS
    displayName: Persistent Volume Class name
    description: The class of the volume; netapp-file-standard, netapp-file-block
    required: false
    value: netapp-file-standard
